variables:
  IMAGE_NAME: akaunting/akaunting
  IMAGE_TAG: akaunting-1.0

stages:
  - test
  - security
  - build

# Test Terraform configurations with Terrascan
terrascan:
  stage: test
  image: accurics/terrascan
  script:
    - terrascan init
    - terrascan scan --config-only --output json > terrascan.json
  artifacts:
    when: always
    paths:
      - terrascan.json
  allow_failure: true

# Test Infrastructure as Code with Checkov
checkov:
  stage: test
  image: bridgecrew/checkov
  script:
    - checkov --directory . --output-file-path checkov.json
  artifacts:
    when: always
    paths:
      - checkov.json
  allow_failure: true

# Open Policy Agent (OPA) Policy Validation
opa_validate:
  stage: security
  image: openpolicyagent/opa
  script:
    - opa test . -v > opa_results.json
  artifacts:
    when: always
    paths:
      - opa_results.json
  allow_failure: true

# Validate Ansible Playbooks
ansible_lint:
  stage: test
  image: cytopia/ansible-lint
  script:
    - ansible-lint playbook.yml
  allow_failure: true

# Upload Reports for Analysis
upload_reports:
  stage: test
  image: python
  needs: ['terrascan', 'checkov', 'opa_validate']
  before_script:
    - pip3 install requests
  script:
    - python3 upload-report.py terrascan.json
    - python3 upload-report.py checkov.json
    - python3 upload-report.py opa_results.json

# Build and Push Docker Image
build_image:
  stage: build
  image: docker:24
  variables:
    DOCKER_USER: $DOCKER_USER
    DOCKER_PASS: $DOCKER_PASS
  services:
    - docker:24-docker:24-dind
  before_script:
    - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
