---
- name: CI/CD Pipeline Setup with Ansible
  hosts: localhost
  tasks:
    - name: Update APK cache
      apk:
        update_cache: yes

    - name: Install necessary packages
      apk:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - gnupg
        - unzip

    - name: Add HashiCorp GPG key (curl)
      command: curl -fsSL https://apt.releases.hashicorp.com/gpg -o /tmp/hashicorp.gpg
      args:
        creates: /tmp/hashicorp.gpg

    - name: Convert GPG key to appropriate format
      command: gpg --dearmor /tmp/hashicorp.gpg -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add HashiCorp APT repository (for future installs)
      copy:
        content: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com focal main"
        dest: /etc/apt/sources.list.d/hashicorp.list
      when: false  # Not needed for Alpine

    - name: Install Terraform using APK (if available)
      apk:
        name: terraform
        state: present
      ignore_errors: yes

    - name: Manually install Terraform if APK install fails
      block:
        - name: Download Terraform binary
          get_url:
            url: "https://releases.hashicorp.com/terraform/{{ lookup('env', 'TF_VERSION') }}/terraform_{{ lookup('env', 'TF_VERSION') }}_linux_amd64.zip"
            dest: /tmp/terraform.zip

        - name: Unzip Terraform binary
          unarchive:
            src: /tmp/terraform.zip
            dest: /usr/local/bin/
            remote_src: yes

        - name: Remove Terraform zip file
          file:
            path: /tmp/terraform.zip
            state: absent
      when: "'terraform' not in ansible_facts.packages"

    - name: Ensure Docker is installed
      apk:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
